name: Build Spacy Wheel

on: [push, workflow_dispatch]

jobs:
  build_wheel:
    runs-on: windows-latest

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Install old setuptools
      # ставим ту версию, при которой spaCy 2.1.9 ещё собирается
      run: python -m pip install "setuptools<58" wheel

    - name: Build wheel
      run: pip wheel spacy==2.1.9 --wheel-dir=wheelhouse --no-build-isolation

    - uses: actions/upload-artifact@v4
      with:
        name: spacy-2.1.9-cp38-win_amd64
        path: wheelhouse/*.whl
